# Bitan Paul - 20BCS6515 || Lab Mst - 1 || 4th Sem

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('/Users/bitanpaul/Documents/Academics/ML/CSVs/real_estate.csv')
df

area    price
0   1000   500000
1   2000  1000000
2   3000  1500000
3   4000  2000000
4   5000  2500000
5   6000  3000000
6   7000  3500000
7   8000  4000000
8   9000  4500000
9  10000  5000000

In [3]:
import seaborn as sns 
sns.scatterplot(x='area', y='price', data=df, color='red', marker='*')
plt.show()

In [4]:
area1=df.drop('price', axis='columns')
area1

area
0   1000
1   2000
2   3000
3   4000
4   5000
5   6000
6   7000
7   8000
8   9000
9  10000

In [5]:
price1=df.drop('area', axis='columns')
price1

price
0   500000
1  1000000
2  1500000
3  2000000
4  2500000
5  3000000
6  3500000
7  4000000
8  4500000
9  5000000

In [6]:
reg=linear_model.LinearRegression()

In [7]:
reg.fit(area1, price1)

LinearRegression()

In [8]:
reg.predict([[3300]]) #give area & it will predict price

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[1650000.]])

In [9]:
reg.predict([[5000]])

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[2500000.]])

In [10]:
reg.coef_


array([[500.]])

In [11]:
reg.intercept_

array([0.])

In [12]:
0+3300*500 # Intercept+Prediction Input*Coefficient=Predicted Value


1650000

In [13]:
0+5000*500

2500000